### ISSUE TITLE
A question about BioBERT

### ISSUE THREAD

**Issue by speedcell4** [LorrinWWW/Pyramid#3]
Hi~

To train on GENIA with [BioBERT](https://github.com/dmis-lab/biobert), I found there are several pre-trained embedding files, which one should I use? And could you please tell me the dimension of BioBERT? 768 or 1024?

- BioBERT-Base v1.1 (+ PubMed 1M)
- BioBERT-Large v1.1 (+ PubMed 1M)
- BioBERT-Base v1.0 (+ PubMed 200K)
- BioBERT-base-Cased (same vocabulary)
- BioBERT-Base v1.0 (+ PubMed 200K + PMC 270K)

**Comment by speedcell4** [comment]
If possible, could you please show me how to load BioBERT? I did no find that part in your code

**Comment by LorrinWWW** [comment]
Thanks for your attention. We choose "BioBERT-Large v1.1 (+ PubMed 1M)" in the paper, where the hidden dimension is 1024. Specifically, you can follow this [instruction](https://huggingface.co/transformers/converting_tensorflow_models.html) to convert tf checkpoint to the format of *transformers*. Then, you can pass the folder path to the argument "model_name" in the "./runs/gen_bert_emb.py" script to generate contextualized embeddings.

However, at this time point, we also recommend to try bert checkpoints already archived [here](https://huggingface.co/models), e.g., "trisongz/biobert_large_cased". In this case, we only need to pass the model name to the argument "model_name" in the "./runs/gen_bert_emb.py" script to generate contextualized embeddings.

**Comment by speedcell4** [comment]
Thank you for your help~
