### ISSUE TITLE
[输入文件]输入文件格式

### ISSUE THREAD

**Issue by NewOrange** [LorrinWWW/Pyramid#5]
你好，请问可以提供输入文件格式，给出输入文件的一些demo么？
谢谢

**Comment by LorrinWWW** [comment]
Copied from README:

> Each dataset is further unified in json and placed in "./datasets/unified/" as "train.{dataset}.json", "valid.{dataset}.json", and "test.{dataset}.json" three files.
>Each json file consists of a **list** of items, and each of item looks like:
>    ```json
>    {
>      "tokens": ["token0", "token1", "token2"],
>      "entities": [
>        {
>          "entity_type": "PER", 
>          "span": [0, 1],
>        },
>        {
>          "entity_type": "ORG", 
>          "span": [2, 3],
>        },
>      ]
>    }
>    ```

Hope that helps.
